# -*- coding: utf-8 -*-
"""Исследовательский анализ недвижимости

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HMXQr5OlWSjYu0DvWVy8l8Gz3n6RXtM

# Исследование объявлений о продаже квартир

**Описание проекта**
В распоряжении находятся данные сервиса *...* — архив объявлений о продаже квартир в Санкт-Петербурге и близлежащих населённых пунктах за несколько лет. Информация представлена в двух видах:

- данные, внесённые пользователями (количество комнат, площадь, высота потолков, дата размещения и др.);
- данные, полученные автоматически из картографических сервисов (расстояние до центра города, аэропорта, парков, водоёмов и др.).

**Цель исследования**
Выявить факторы, влияющие на рыночную стоимость квартир, и на их основе построить систему, способную:

- оценивать адекватность цены объекта;
- выявлять аномалии и возможные мошеннические объявления.

**Задачи исследования**

1. Провести предобработку данных (обработка пропусков, дубликатов, выбросов).
2. Провести исследовательский анализ данных (EDA):

   * изучить распределения основных признаков;
   * выявить корреляции между параметрами и стоимостью жилья;
   * определить факторы, оказывающие наибольшее влияние на цену.
3. Выявить закономерности, позволяющие построить модель для прогнозирования стоимости.

**Ожидаемый результат**

* Описание параметров, влияющих на стоимость квартир.
* Метрики и критерии для выявления аномалий и мошеннических объявлений.
* Основы для разработки автоматизированной системы мониторинга рынка недвижимости.
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

data = pd.read_csv('real_estate_data.csv', sep='\t', decimal ='.')

data.info()

data.head(20)

data.hist(figsize=(10, 10))
plt.show()

"""**Вывод**

Таблица открыта и датафрейм изучен, данные загружены корректно и доступны для анализа. Построенные гистограммы позволили получить общее представление о распределении признаков. Уже на этом этапе можно заметить отдельные отклонения и потенциальные аномалии в данных. В дальнейшем я рассмотрю их подробнее, чтобы понять их природу и влияние на исследование.

"""

data.duplicated().sum()

data.isna().sum()

"""Пойдем по порядку:

высота потолков (м) - количественная переменная - возьмем медианное значение

всего этажей в доме - пропусков мало, выкидываем строки

жилая площадь в квадратных метрах (м²) - количественная, берем медиану, чтобы не исказить данные

апартаменты (булев тип) - значит это не апартаменты

площадь кухни в квадратных метрах (м²) - количество, берем медиану

число балконов - говорит о том, что балконов в квартире нет

название населённого пункта - категориальная переменная, без нее будет сложно оценить оставшиеся данные

расстояние до ближайшего аэропорта в метрах (м) - количественная, берем медиану, данных много, поэтому неоходимо это учитывать в дальнейшем

расстояние до центра города (м) - количественная, берем медиану, данных много, поэтому неоходимо это учитывать в дальнейшем

число парков в радиусе 3 км - количественная, берем медиану, данных много, поэтому неоходимо это учитывать в дальнейшем

расстояние до ближайшего парка (м) - количественная, берем медиану, данных много, поэтому неоходимо это учитывать в дальнейшем

число водоёмов в радиусе 3 км - количественная, берем медиану, данных много, поэтому неоходимо это учитывать в дальнейшем

расстояние до ближайшего водоёма (м) - количественная, берем медиану, данных много, поэтому неоходимо это учитывать в дальнейшем

сколько дней было размещено объявление (от публикации до снятия) - скорее всего объявление сняли день в день

Большое кол-во пропусков оказалось в данных, которые заполняются не пользователями, необходимо сообщить о проблеме.

Заменяем все по порядку, ставим "0" и медианные значения
"""

data['is_apartment'] = data['is_apartment'].fillna(value=False)
data['balcony'] = data['balcony'].fillna(value='0')

data['ceiling_height'] = data['ceiling_height'].fillna(data['ceiling_height'].median())
data = data.dropna(subset=['locality_name', 'floors_total'])
area_co = data['living_area'].dropna()/data['total_area']
data_area_co = area_co.mean()
data['living_area'] = data['living_area'].fillna(data['total_area']*data_area_co)
kitchen_co = data['kitchen_area'].dropna()/data['living_area']
kitchen_co_mean = kitchen_co.mean()
data['kitchen_area'] = data['kitchen_area'].fillna(data['living_area']*kitchen_co_mean)
data.isna().sum()

data[data['total_area'].astype(float) < data['living_area'].astype(float) + data['kitchen_area'].astype(float)].shape[0]

"""Проверила квартиры, у которых сумма жилой площади и площади кухни больше общей, что невозможно.

Пропуски можно заполняю так: сначала вычисляем среднее отношение жилой площади к общей, это будет наш коэффициент жилой площади. Далее в строках с пропусками умножаем общую площадь на этот коэффициент, получая жилую площадь.
"""

data['parks_nearest'].describe()

data['ponds_nearest'].describe()

data.isna().sum()

data.dtypes

data['last_price'] = pd.to_numeric(data['last_price'])

data['total_area'] = pd.to_numeric(data['total_area'])

data['first_day_exposition'] = pd.to_datetime(data['first_day_exposition'], format='%Y-%m-%dT%H:%M:%S')

data['ceiling_height'] = pd.to_numeric(data['ceiling_height'])

data['floors_total'] = pd.to_numeric(data['floors_total'])

data['living_area'] = pd.to_numeric(data['living_area'])

data['is_apartment'] = data['is_apartment'].astype('bool')

data['kitchen_area'] = pd.to_numeric(data['kitchen_area'])

data['balcony'] = pd.to_numeric(data['balcony'])

data['airports_nearest'] = pd.to_numeric(data['airports_nearest'])

data['parks_around3000'] = pd.to_numeric(data['parks_around3000'])

data['cityCenters_nearest'] = pd.to_numeric(data['cityCenters_nearest'])

data['parks_nearest'] = pd.to_numeric(data['parks_nearest'])

data['ponds_around3000'] = pd.to_numeric(data['ponds_around3000'])

data['ponds_nearest'] = pd.to_numeric(data['ponds_nearest'])

data['days_exposition'] = pd.to_numeric(data['days_exposition'])

data.info()

"""Выше изменила типы данных для удобной работы с информацией. Далее поиск уникальных значений и поиск неявных дубликатов."""

data['locality_name'].unique()

data['locality_name'] = (
    data['locality_name']
    .str.replace('ё', 'е')
    .replace(['поселок Калитино', ...], 'Кальтино', regex=True)
    .replace(['Кудрово'], 'деревня Кудрово', regex=True)
    .replace(['поселок Гарболово', 'деревня Гарболово'], 'Гарболово', regex=True)
    .replace(['поселок Калитино', 'деревня Калитино'], 'Калитино', regex=True)
    .replace(['поселок Мурино', ], 'Мурино', regex=True)
)

centr_data = data.sort_values('locality_name')

centr_data_co = centr_data['cityCenters_nearest'].median()

data['cityCenters_nearest'] = data['cityCenters_nearest'].fillna(centr_data_co)

air_data = data.sort_values('airports_nearest')
air_data_co = air_data['airports_nearest'].median()
data['airports_nearest'] = data['airports_nearest'].fillna(air_data_co)

data.isna().sum()

data.info()

"""**Вывод**

На этапе предобработки данных было выявлено, что около 5000 строк содержат пропуски из-за системного бага, что ограничивает точность дальнейших расчётов. Я привела данные к корректным типам, обработала часть пропусков и внесла необходимые изменения. Это позволит использовать датасет более эффективно и получить максимально полезные результаты на следующих шагах анализа.

"""

#Создала новый столбец с ценой за м3
data['price_metr'] = data['last_price']/data['total_area']
data['price_metr'] = data['price_metr'].round(2)
#Создала столбец с днем недели
data['weekday_publ'] = data['first_day_exposition'].dt.weekday
#Создала столбец с месяцем выставления объявления
data['month_publ'] = data['first_day_exposition'].dt.month
#Создала столбец с годом
data['year_publ'] = data['first_day_exposition'].dt.year

#Создала функцию, которая разделяет этаж на три категории
def category(row):
    if row['floor'] == row['floors_total']:
        return 'последний'
    if row['floor'] == 1:
        return 'первый'
    else:
        return 'другой'
data['floor_category'] = data.apply(category, axis=1)

#Превращаю метры в километры и возвращаю тип данных к целому числу
data['centr_km'] = data['cityCenters_nearest']/1000
data['centr_km'] = data['centr_km'].astype(int)

"""**Вывод**

На данном этапе я рассчитала цену за квадратный метр и добавила новые признаки, которые помогут в дальнейшем анализе. Были созданы столбцы с днём недели, месяцем и годом публикации объявления, а также дополнительный столбец с расстоянием в километрах (вместо метров) для удобства вычислений. Кроме того, выполнена категоризация этажей, что позволит более детально учитывать фактор расположения квартиры в доме.

"""

#Рассмоатриваю общую площадь квартиры в квадратных метрах (м²)
data['total_area'].hist(bins=50)

data['total_area'].hist(bins = 300, figsize = (15, 7), color='#A7D2CB')
plt.xlim(10, 100)

plt.title('Распределение значений общей площади')
plt.xlabel('Площадь')
plt.ylabel('Количество объявлений')
plt.show()

data['total_area'].describe()

"""**Вывод**

Анализ распределения показал, что значения площади квартир в целом выглядят реалистично, за исключением аномально больших значений. По гистограмме было принято решение ограничить данные и удалить квартиры с площадью более 300 м², так как они искажают общую картину и не отражают типичный рынок.

"""

data = data.query('total_area<300')

data['total_area'].describe()

data['total_area'].hist(bins=300, figsize = (10, 8))
plt.xlim(10, 100)

plt.title('Распределение значений общей площади')
plt.xlabel('Площадь')
plt.ylabel('Количество объявлений')
plt.show()

data['living_area'].hist(bins=100, figsize=(10,8))
plt.xlim(10, 70)

plt.title('Распределение значений жилой площади')
plt.xlabel('Площадь')
plt.ylabel('Количество объявлений')
plt.show()

data['living_area'].describe()

data.plot(y='living_area', style="o", figsize=(8,6), grid=True)

data = data.query('living_area>10')

data['living_area'].describe()

data['living_area'].hist(bins=100, figsize=(10,8))
plt.xlim(10, 70)

plt.title('Распределение значений жилой площади')
plt.xlabel('Площадь')
plt.ylabel('Количество объявлений')
plt.show()

"""Такие же дела обстоят с жилой площадью, отбрасываем вбросы и неверные значения для расчетов.

"""

data['kitchen_area'].hist(bins=100, figsize=(10,8))
plt.xlim(2, 60)

plt.title('Распределение значений площади кухни')
plt.xlabel('Площадь')
plt.ylabel('Количество объявлений')
plt.show()

data['kitchen_area'].describe()

data = data.query('kitchen_area<60 and kitchen_area>5')

data['kitchen_area'].describe()

data['last_price'].hist(bins=100, figsize=(10,8))
plt.xlim(0, 60000000)

plt.title('Распределение значений цены объекта')
plt.xlabel('Цена объекта')
plt.ylabel('Количество объявлений')
plt.show()

data['last_price'].describe()

def price_category(dol):
    if dol['last_price'] <= 500000:
        return dol['last_price']*100
    elif dol['last_price'] > 100000000:
        return dol['last_price']/100
    else:
        return dol['last_price']
data['price_category'] = data.apply(price_category, axis=1)

data['price_category'].hist(bins=100, figsize=(10,8))
plt.xlim(0, 60000000)

plt.title('Распределение значений цены объекта')
plt.xlabel('Цена объекта')
plt.ylabel('Количество объявлений')
plt.show()

data['price_category'].describe()

data['rooms'].hist(bins=100, figsize=(10,8))
plt.xlim(0, 10)

plt.title('Распределение значений по количеству комнат')
plt.xlabel('х-комнат')
plt.ylabel('Количество объявлений')
plt.show()

data['rooms'].describe()

data['ceiling_height'].hist(bins=100, figsize=(10,8))
plt.xlim(0, 20)

plt.title('Распределение значений высоты потолка')
plt.xlabel('Высота потолка')
plt.ylabel('Количество объявлений')
plt.show()

data['ceiling_height'].describe()

data.plot(y='ceiling_height', style="o", figsize=(4,10), grid=True, ylim=(0,6))

data = data.query('ceiling_height>2.4 and ceiling_height<6')

data['ceiling_height'].describe()

data['ceiling_height'].hist(bins=100, figsize=(10,8))
plt.xlim(2.4, 6)

plt.title('Распределение значений высоты потолка')
plt.xlabel('Высота потолка')
plt.ylabel('Количество объявлений')
plt.show()

data['floor_category'].hist(bins=10)

data['floors_total'].hist(bins=100, figsize=(10,8))
plt.xlim(0, 20)

plt.title('Распределение значений многоэтажек')
plt.xlabel('количество этажей')
plt.ylabel('Количество объявлений')
plt.show()

data['floors_total'].describe()

data['cityCenters_nearest'].hist(bins=100, figsize=(10,8))
plt.xlim(0, 40000)

plt.title('Расстояние до центра города в метрах')
plt.xlabel('Расстояния м до центра')
plt.ylabel('Количество объявлений')
plt.show()

data.plot(y='cityCenters_nearest', style="o", figsize=(10,10), grid=True)

data['cityCenters_nearest'].describe()

data['parks_nearest'].hist(bins=100, figsize=(10,8))
plt.xlim(0, 1000)

plt.title('Парки поблизости')
plt.xlabel('Расстояние от парка в м')
plt.ylabel('Количество объявлений')
plt.show()

data.plot(y='parks_nearest', style="o", figsize=(10,10), grid=True)

data['parks_nearest'].describe()

# код ревьюера
data.shape[0] / 23699

"""**Вывод**

Я очистила данные от выбросов (крайне низких и высоких значений) и создала функцию для автоматизации этой обработки.

По построенным гистограммам можно выделить общие тенденции предпочтений покупателей недвижимости:

* площадь квартиры чаще всего составляет около **42–48 м²**;
* жилая площадь — **18–19 м²** или **30–33 м²**;
* площадь кухни — **9–10 м²**;
* наиболее популярный ценовой диапазон — около **5 млн рублей**;
* количество комнат обычно **от 1 до 3**;
* высота потолков в среднем около **2,65 м**;
* по этажности заметно, что чаще избегают крайних (первого и последнего), но при этом и они остаются востребованными;
* покупатели чаще выбирают квартиры в **5- и 9-этажных зданиях**;
* оптимальное расстояние до центра города — **10–15 км**;
* предпочтительно, чтобы рядом находился парк в пределах **500 м**.

Эти параметры дают общее представление о типичном портрете объекта недвижимости, пользующегося спросом у покупателей.

"""

data['days_exposition'].hist(bins=10)

data['days_exposition'].describe()

"""Обычно продажа квартиры занимает до 76 дней со дня размещения объявления, те что продаются дольше, уже считаются довольно долгой продажей. В нашей таблице самой длинной продажой является 1572 дня.


"""

data.plot( y='last_price', x='total_area', kind='scatter', figsize=(8,6), alpha=0.7, sharex=False, grid=True)

data.plot( x='living_area', y='last_price', kind='scatter', figsize=(8,6), alpha=0.7, sharex=False, grid=True)

data.plot( x='kitchen_area', y='last_price', kind='scatter', figsize=(8,6), alpha=0.7, sharex=False, grid=True)

data.plot( x='rooms', y='last_price', kind='scatter', figsize=(8,6), alpha=0.7, sharex=False, grid=True)

data.groupby('ceiling_height')['last_price'].mean().plot(kind='bar', figsize=(15, 8))

plt.title('Средняя цена квартиры в зависимости от высоты потолков')
plt.xlabel('Высота потолков')
plt.ylabel('Средняя цена квартиры')

plt.show()

data.plot(x='ceiling_height', y='last_price', kind='scatter', figsize=(10,10))

# код ревьюера

data.groupby('floor_category')['last_price'].mean().plot(kind='bar', figsize=(11, 7), color='#73A9AD')

plt.xticks(rotation=0)
plt.title('Средняя цена квартиры в зависимости от категории этажа', size=15)
plt.xlabel('Категория этажа', size=12)
plt.ylabel('Средняя цена квартиры', size=12)

plt.show()

data.plot( x='weekday_publ', y='last_price', kind='hexbin', gridsize=20, figsize=(8,6), alpha=0.7, sharex=False, grid=True)

data.plot( y='month_publ', x='last_price', kind='hexbin', gridsize=20, figsize=(8,6), alpha=0.7, sharex=False, grid=True)

data.plot( y='year_publ', x='last_price', kind='hexbin', gridsize=20, figsize=(8,6), alpha=0.7, sharex=False, grid=True)

"""Делаем вывод о том, что на покупку недвижимости влияет площадь всего объекта, кухни и жилая площадь, цена, год, месяц и день недели, и этаж, на котором располагается квартира."""

df = data.pivot_table(index='locality_name', values=['last_price', 'total_area'], aggfunc=['sum','mean', 'count'])

df.head()

df.columns = ['sum_price', 'sum_area','mean_price', 'mean_area', 'count_price', 'count_area']

top_localities = df.sort_values(by='count_price', ascending=False).head(10)

top_localities

top_localities['mean_value'] = top_localities['sum_price']/top_localities['sum_area']
top_localities

top_localities['mean_value2'] = top_localities['mean_price']/top_localities['mean_area']
top_localities

high_local = top_localities['mean_value'].idxmax()
low_local = top_localities['mean_value'].idxmin()

high_local

low_local

"""Самым дорогим квадратным метром оказался Санкт-Петербург, а самым бюджетным из этой выборки - Выборг


"""

top_localities.plot(x='mean_value', y='count_price', kind='hexbin', gridsize=20, figsize=(8,6), sharex=False, grid=True)

df2 = data.pivot_table(index='locality_name', values=['last_price', 'living_area'], aggfunc=['mean', 'count'])
df2.columns = ['mean_price2', 'mean_area2', 'count_price2', 'count_area2']
df2.head()

df2.plot(x='mean_area2', y='mean_price2', kind='hexbin', gridsize=20, figsize=(8,6), sharex=False, grid=True)

df3 = data.pivot_table(index='locality_name', values=['last_price', 'kitchen_area'], aggfunc=['mean', 'count'])
df3.columns = ['mean_price3', 'mean_area3', 'count_price3', 'count_area3']
df3.plot(x='mean_area3', y='mean_price3', kind='hexbin', gridsize=20, figsize=(8,6), sharex=False, grid=True)

df4 = data.pivot_table(index='locality_name', values=['last_price', 'rooms'], aggfunc=['mean', 'count'])
df4.columns = ['mean_price4', 'mean_area4', 'count_price4', 'count_area4']
df4.plot(x='mean_area4', y='mean_price4', kind='hexbin', gridsize=20, figsize=(8,6), sharex=False, grid=True)

data['floor_category'].hist(bins=10)

df5 = data.pivot_table(index='locality_name', values=['last_price', 'weekday_publ'], aggfunc='mean')
df5.columns = ['mean_price5', 'mean_area5']
df5.plot(x='mean_area5', y='mean_price5', kind='hexbin', gridsize=20, figsize=(8,6), sharex=False, grid=True)

df6 = data.pivot_table(index='locality_name', values=['last_price', 'month_publ'], aggfunc='mean')
df6.columns = ['mean_price6', 'mean_area6']
df6.plot(x='mean_area6', y='mean_price6', kind='hexbin', gridsize=20, figsize=(8,6), sharex=False, grid=True)

df7 = data.pivot_table(index='locality_name', values=['last_price', 'year_publ'], aggfunc='mean')
df7.columns = ['mean_price7', 'mean_area7']
df7.plot(x='mean_area7', y='mean_price7', kind='hexbin', gridsize=20, figsize=(8,6), sharex=False, grid=True)

"""**Вывод**

Анализ наиболее «продаваемых» характеристик объектов показал следующие тенденции:

* средняя жилая площадь популярных квартир составляет около **30 м²**;
* площадь кухни чаще всего находится в диапазоне **7,5–9 м²**;
* наибольшим спросом пользуются квартиры с **двумя комнатами**;
* распределение по этажам остаётся аналогичным предыдущим наблюдениям (предпочитаются не первый и не последний этаж, но крайние этажи также находят покупателей);
* по дням недели максимальная активность продаж приходится на **четверг**;
* на рынке заметна сезонность: пик продаж наблюдается **с мая по июль**, затем активность возвращается в конце августа — начале сентября;
* наиболее активные годы по количеству продаж — **2017 и 2018**.

Эти результаты позволяют выделить типичные параметры квартир, которые наиболее часто находят покупателя, и учесть сезонно-временные факторы.

"""

data_centr_spb = data.loc[data['locality_name']=='Санкт-Петербург']
price_spb = data_centr_spb.groupby('centr_km')['last_price'].mean()
price_spb

price_spb.columns = ['centr_km_mean', 'last_price_mean']
price_spb.plot(x='centr_km_mean', y='last_price_mean', kind='bar', sharex=False, grid=True, figsize=(10,5))

"""**Вывод**

В рамках исследования я изучила данные датафрейма: построила гистограммы и графики, рассчитала средние значения, удалила пропуски и обработала отсутствующие данные, отсортировала информацию.

**Итоги по влиянию признаков на цену квартиры:**

* **Год размещения объявления** не оказал сильного влияния на цену, однако наибольшая активность продаж наблюдалась в 2016–2017 гг.
* **Месяц публикации** оказал более заметное влияние: наиболее «дорогими» оказались февраль, март, апрель и ноябрь.
* **День недели** не дал однозначной зависимости цен, но мы отметили, что четверг — один из самых популярных дней для выставления объявлений.
* **Этаж:** квартиры на первом этаже чаще дешевле остальных.
* **Количество комнат:** чаще всего квартиры с 2–6 комнатами продаются охотнее. Прямая зависимость цены больше связана с общей площадью, чем с самим количеством комнат.
* **Кухня:** её площадь напрямую не определяет цену, но в целом большие кухни встречаются у более просторных квартир, а значит — и более дорогих.
* **Общая и жилая площадь:** ключевой фактор — чем больше площадь, тем дороже квартира. Для анализа мы рассчитали цену за квадратный метр.
* **Расположение:** квартиры в Санкт-Петербурге почти вдвое дороже по цене за квадратный метр, чем, например, в Выборге. Удалённость от центра также играет важную роль: чем дальше, тем дешевле.

**Характеристика наиболее продаваемых квартир по нашим данным:**

* дома в 5 и 9 этажей;
* не первый этаж;
* общая площадь около **40 м²**;
* кухня около **5 м²**;
* высота потолков примерно **2,65 м**;
* расстояние до центра — около **10 км**;
* цена — около **5 млн рублей**.

**Выводы и рекомендации:**

* Наибольшее влияние на цену оказывают: площадь квартиры (жилая и общая), удалённость от центра, расположение квартиры в городе, а также этаж.
* Необходимо дополнительно проверить корректность работы сервисов, которые автоматически считают расстояния до центра, парков, водоёмов и других объектов.
* С учётом всех выявленных факторов можно построить алгоритм для автоматической оценки рыночной стоимости квартиры, что позволит выявлять аномалии и потенциально мошеннические объявления.

"""