# -*- coding: utf-8 -*-
"""Исследование данных  по продажам

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tODEYiNdZDx00Z1jHy1dAK5RSbPvzDc

# Исследование данных о продаже компьютерных игр.
    
**Описание проекта:** В современном мире компьютерные игры стали неотъемлемой частью жизни людей. Они не только развлекают, но и объединяют, развивают навыки и даже помогают справляться со стрессом.
    
**Цель исследования:** Определить осноные факторы, влияющие на рыночную стоимость компьютерных игр интернет-магазина «Стримчик».
    
Ход исследования:
    - Подготовка данных: загрузка и изучение общей информации из предоставленного датасета.
    - Предобработка данных: обработка пропущенных значений, корректировка типа данных, явных и неявных дубликатов и других аномалий.
    - Расширение набора данных: добавление новых столбцов, таких как сумма продаж по всем регионам и другие необходимые.
    - Исследовательский анализ данных: изучение основных параметров объектов, их распрделения, зависимости стоимость от различных характеристик, выявление и обработка аномалий.
    
Общий вывод:резюмирование полученных результатов, формулировка ключевых выводов и рекомендаций.
    
С помощью данного исследования мы стремимся дать всесторонний анализ рынка компьютерных игр на различных платформах, что станет началом для дальнейших исследований и разработки автоматизированной систем мониторинга

## Импорт библиотек и чтение файла
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats as st
from scipy.stats import ttest_ind
import seaborn as sns

data = pd.read_csv('games.csv')

def analysis_df (data):
    print(data.info())
    print(data.isna().sum())
    print(data.duplicated().sum())

analysis_df(data)

"""### Вывод

Назвали наш исследуемый датафрейм - data. По общей информации можно увидеть, что есть пропущенные значения, строк в датафрейме достаточно большое количество > 16 тысяч.

В данных 11 столбцов с названием, платформой, годом выпуска, жанром, продажам в Северной Америке, Европе, Японии и других регионах, оценку критиков, пользователей и рейтига ESRB (англ. Entertainment Software Rating Board).

Необходимо исправить название столбцов, посмотреть и изменить типы данных в некоторых столбцах.

## Подготовка данных

### Замена названий столбцов
"""

data.columns = data.columns.str.lower()

data.head()

"""### Изучаем наличие пропусков"""

data.isna().sum()

pd.DataFrame(round(data.isna().mean()*100,1)).style.background_gradient('coolwarm')

"""Пропусков в названии всего два, можно заменить на название 'unknown', так как почти все действия мы будем производить именно с числовыми значениями.

Пропуски в годах выпуска и всех видах рейтинга и оценок постараемся заполнить данными, которые уже есть в таблице. С помощью цикла мы пройдемся по всему датафрейму найдем одинаковые названия игр - ведь в них уже может быть проставлен рейтинг или год выпуска.
"""

data['name'] = data['name'].fillna('unknown')

for d in range(len(data)):
    if pd.isna(data.loc[d, 'year_of_release']):
        same_name = data[data['name'] == data.loc[d, 'name']]
        if not same_name['year_of_release'].isna().all():
            data.loc[d, 'year_of_release'] = same_name['year_of_release'].dropna().iloc[0]

data['critic_score'].unique()

data['critic_score'].describe()

data['user_score'].unique()

data['user_score'].describe()

"""Данные довольно сильно разбросаны, поэтому проходимся по плану циклом для заполнения пропусков."""

for d in range(len(data)):
    if pd.isna(data.loc[d, 'critic_score']):
        same_score = data[data['name'] == data.loc[d, 'name']]
        if not same_score['critic_score'].isna().all():
            data.loc[d, 'critic_score'] = same_score['critic_score'].dropna().iloc[0]

for d in range(len(data)):
    if pd.isna(data.loc[d, 'rating']):
        same_rating = data[data['name'] == data.loc[d, 'name']]
        if not same_rating['rating'].isna().all():
            data.loc[d, 'rating'] = same_rating['rating'].dropna().iloc[0]

for d in range(len(data)):
    if pd.isna(data.loc[d, 'user_score']):
        same_user = data[data['name'] == data.loc[d, 'name']]
        if not same_user['user_score'].isna().all():
            data.loc[d, 'user_score'] = same_user['user_score'].dropna().iloc[0]

for d in range(len(data)):
    if pd.isna(data.loc[d, 'genre']):
        same_genre = data[data['name'] == data.loc[d, 'name']]
        if not same_genre['genre'].isna().all():
            data.loc[d, 'genre'] = same_genre['genre'].dropna().iloc[0]

data.isna().sum()

"""Сразу видим, что не все пропуски получилось убрать, в годах их не очень много, заменим на ноль, чтобы не сбивать подсчеты, учитывая это в дальнейшем.

По столбцам с рейтингом оставляем 'nan', так как пропусков очень много и медианное значение может немного исказить результаты.

2 пропуска в столбце жанров не получилось найти через цикл, поэтому ставим пустую строку.
"""

data = data.dropna(subset=['year_of_release', 'genre'])

data.isna().sum()

"""Проверяем работу с пропусками, все, что заменили - заменилось. Причинами пропусков могло быть отсутствие рейтингов из-за, например, недавнего выхода игры или. отсутствия самих рейтингов, или сбоя программы, которая собирала эту информацию - т.е. технический сбой или человеческий фактор(что менее вероятно с учетом кол-ва пропусков)

### Находим строки с рейтингом 'tbd', определяем его значение
"""

row = data[data['user_score']=='tbd']

row

"""tbd - to be determined - предположу, что это обозначения для игр, чей рейтинг еще не определен/отсутствует и таких значений довольно много.

В дальнейшем создам копию датафрейма data_next, где отсутствуют tbd, чтобы была возможность рассчитать все операции, именно поэтому не меняю здесь тип данных в этом столбце.

И не удаляю сразу эти значения, ведь в этих строках много полезной информации для рассчета.
"""

data['user_score'] = data['user_score'].replace('tbd', np.nan)
data['user_score'] = pd.to_numeric(data['user_score'], errors='coerce')

data.head()

data['user_score'].unique()

"""### Работа с изменением типа данных"""

data['year_of_release'] = data['year_of_release'].astype(int)

"""Изменяем тип данных для дальнейших вычислений, тк год не бывает не целым числом. Все остальные типы пока не трогаю, чтобы поработать и со строчными и с числовыми данными.

### Создаем новый столбец 'sales', в котором соединены все продажи.
"""

data['sales'] = data['na_sales'] + data['eu_sales'] + data['jp_sales'] + data['other_sales']
data.head()

"""### Проверяем дубликаты"""

data.duplicated().sum()

data[data[['name', 'platform','year_of_release']].duplicated(keep=False)]

data.info()

data = data.drop_duplicates(subset=['name', 'platform', 'year_of_release', 'genre'], keep='first').reset_index(drop=True)

data.info()

"""### Вывод:

- Подготовили данные для дальнейшей работы.

- Заменили названия столбцов на строчные.

- Преобразовали данные в необходимый тип.

- Удалили и заполнили пропуски, часть пропусков оставили, так как их было очень много.

- Посчитали суммарные продажи и выяснили что значит 'tbd'.

## Исследовательский анализ данных

### Изучим сколько игр выпускалось в разные годы.
"""

data.groupby('year_of_release')['name'].count().plot(
kind='bar',
figsize=(10,10),
xlabel='Год выпуска',
ylabel='Количество игр',
title='Выпуск игр в разные годы',
xlim=(1, 2016)
      )

"""По графику мы видим как, начиная с 1990 активно развиваются и появляются новые игры, пик приходится на 2000-2010, после 2011 наблюдатся спад, но игры также выходят в большом количестве.

Все данные важны для изучения, но изучим 21 век с максимальным ростом, начиная с 2000 года.

### Продажи по платформам
"""

data.groupby('platform')['sales'].sum().sort_values(ascending=False).plot(kind='bar',
figsize=(10,10),
xlabel='Игровая платформа',
ylabel='Сумма продаж',
title='Продажи игр на разных платформах'
       )

"""По графику мы видим лидеров продаж - 'DS', 'PS2', 'PS3', 'Wii', 'X360'

Ограничим изучение данных 2000-2016 годами, обновим датафрейм и перепроверим.
"""

data = data[data['year_of_release']>1999]
data['year_of_release'].unique()

"""### Прогноз на 2017 год.

Создаем сгруппированный датафрейм по топ лидерам по продажам и сравнваем по годам
"""

platform_sum = data.groupby(['platform', 'year_of_release'])['sales'].sum().reset_index()
platform_max = platform_sum[platform_sum['platform'].isin(['DS', 'PS2', 'PS3', 'Wii', 'X360'])]
platform_max.groupby('platform')['sales'].sum()

platform_max.sort_values(by='sales', ascending=False).head(20)

"""Делаем вывод о том, что самым продаваемым была платформа PS2 на протяжении примерно 2001-2005, также не сильно отставала платформа Wii но уже примерно в 2007-2009"""

platform_max.sort_values(by='year_of_release', ascending=False).head(20)

"""Говоря об этом рейтинге на "сегодняшний" день, то можно заметить что все платформы уменьшают свои продажи в течение последних нескольких лет"""

platform_max.groupby('year_of_release')['platform'].count().plot(
kind='bar',
figsize=(10,8),
xlabel='Год выпуска игры',
ylabel='Количество платформ',
title='Количество платформ лидеров продаж'
    )

"""Пиком кол-ва платформ был 2006-2011, тогда 5 из 5 лидеров были на рынке.

Также посмотрим суммы продаж лидеров за все года в миллионах
"""

platform_ps_two = data[data['platform']=='PS2']
platform_ps_two.groupby(['year_of_release', 'platform'])['sales'].sum().plot(
kind='bar',
figsize=(10,8),
xlabel='Год выпуска игры PS2',
ylabel='Выручка PS2',
title='PS2 Анализ'
    )

platform_x = data[data['platform']=='X360']
platform_x.groupby(['year_of_release','platform'])['sales'].sum().plot(
kind='bar',
figsize=(10,8),
xlabel='Год выпуска игры X360',
ylabel='Выручка X360',
title='X360 Анализ'
    )

platform_ps_three = data[data['platform']=='PS3']
platform_ps_three.groupby(['year_of_release', 'platform'])['sales'].sum().plot(
kind='bar',
figsize=(10,8),
xlabel='Год выпуска игры PS3',
ylabel='Выручка PS3',
title='PS3 Анализ'
    )

platform_wii = data[data['platform']=='Wii']
platform_wii.groupby(['year_of_release', 'platform'])['sales'].sum().plot(
kind='bar',
figsize=(10,8),
xlabel='Год выпуска игры Wii',
ylabel='Выручка Wii',
title='Wii Анализ'
    )

platform_ds = data[data['platform']=='DS']
platform_ds.groupby(['year_of_release', 'platform'])['sales'].sum().plot(
kind='bar',
figsize=(10,8),
xlabel='Год выпуска игры DS',
ylabel='Выручка DS',
title='DS Анализ'
    )

"""По построенным графикам мы видим, что все "бывшие" лидеры сдают позиции и падают в выручке примерно с 2009-2012 гг"""

platform_max.groupby(['year_of_release', 'platform'])['sales'].sum().plot(kind='barh', figsize=(6, 20),
title='Распределение суммы продаж по годам и платформам',
xlabel='Год выпуска',
ylabel='Сумма продаж'
     )

platform_max.groupby(['year_of_release', 'platform'])['sales'].sum().sort_values().plot(kind='barh', figsize=(6, 20),
title='Распределение суммы продаж по годам и платформам',
xlabel='Год выпуска',
ylabel='Сумма продаж'
     )

"""График получился довольно длинный, это не очень удобно для просмотра, но можно выделить период с 2000 по 2015 - как максимально прибыльный период.

Если рассматривать отдельно каждую платформу, то можно предоложить, что в год запуска нового продукта - продажи довольно низкие или продукт выходит под завершение года. Каждое новое устройство они стараются производить каждые 4-6 лет. Проверим это по графику с платформами еще раз.

### Потенциально прибыльные компании
"""

data.groupby(['year_of_release', 'platform'])['sales'].sum().plot(kind='bar', figsize=(100, 6),
title='Распределение суммы продаж по годам и платформам',
xlabel='Год выпуска',
ylabel='Сумма продаж'
     )

"""Каждая новая платформа с самого начала довольно быстро появлялись - 1-3 года требовалось компаниям для создания чего-то нового."""

data_future = data[data['year_of_release']>2012]
data_future.groupby(['year_of_release', 'platform'])['sales'].sum().plot(kind='bar', figsize=(20, 6),
title='Распределение суммы продаж по годам и платформам',
xlabel='Год выпуска',
ylabel='Сумма продаж'
     )

"""Изучим график. Так как почти все предыдущие запуски имели пик продаж, и после него постепенное затухание. Можно сделать вывод о том, что перспективами вложениями в 2017 году будут = XOne и PS4, остальные уже идут на сильное затухание.

### Построение диграммы размаха.
"""

data_future.groupby(['platform'])['sales'].sum().plot.box(figsize=(10, 6),
title='Усатый график по продажам',
     )

for row in data['platform'].unique():
    genre = data[data['platform']==row]
    genre.plot.box(
x='platform',
y='sales',
title=row,
ylim=(0,0.8),
grid=True
     )

for row in data_future['platform'].unique():
    genre = data_future[data_future['platform']==row]
    genre.plot.box(
x='platform',
y='sales',
title=row,
ylim=(0,0.8),
grid=True
     )

data_future.groupby(['platform'])['sales'].sum().describe()

data_future['platform'].unique()

"""Построили график с усами или диаграмму размаха. Видим зеленый - это медиана - примерно 230млн, Максимум чуть больше 1.2 млрд, минимум чуть меньше миллиона. 25% - примерно 75 млн, 75% - около 435 млн."""

plt.figure(figsize=(13, 8))
sns.boxplot(data=data_future, y='sales', x='platform')

plt.title('Продажи по перспективным платформам')
plt.xlabel('Платформы')
plt.ylabel('Общие продажи')
plt.ylim(0, 3)

plt.show()

"""### Влияние на продажи внутри одной платформы отзывы пользователей и критиков. Построение диаграммы рассеяния. Расчет корреляции.
Возьмем за основу платформу ps2 как самую крупную за историю продажи игр.
"""

platform_ps_two.plot(
x='critic_score',
y='sales',
kind='scatter',
alpha=0.4,
title='Продажи и оценка критиков',
xlabel='Оценка критиков',
ylabel='Сумма продаж'
            )

"""На диаграмме видим небольшую зависимость, что чем больше оценка критиков - тем больше продаж."""

platform_ps_two_next = platform_ps_two[platform_ps_two['user_score']!='tbd']
platform_ps_two_next = platform_ps_two_next[platform_ps_two_next['user_score']!='nan']
platform_ps_two_next['user_score'] = platform_ps_two_next['user_score'].astype(float)

platform_ps_two_next.plot(
x='user_score',
y='sales',
kind='scatter',
alpha=0.4,
title='Продажи и оценка пользователей',
xlabel='Оценка пользователей',
ylabel='Сумма продаж'
            )

"""На диграмме видим не сильную, но зависимость - чем выше оценка пользователей - тем больше продаж"""

data_future['critic_score'].corr(data['sales'])

data_next = data_future[data_future['user_score']!='tbd']
data_next = data_next[data_next['user_score']!='NaN']
data_next['user_score'] = data_next['user_score'].astype(float)

data_next['user_score'].corr(data_next['sales'])

"""Корреляция с оценками критиков больше, чем с оценками пользвателей. Оценки критиков"""

for row in data['platform'].unique():
    platform = data[data['platform']==row]
    platform.plot(
x='critic_score',
y='sales',
kind='scatter',
alpha=0.4,
title=row,
xlabel='Оценка критиков',
ylabel='Сумма продаж'
            )

for row in data['platform'].unique():
    platform = data[data['platform']==row]
    platform = platform[platform['user_score']!='tbd']
    platform = platform[platform['user_score']!='nan']
    platform['user_score'] = platform['user_score'].astype(float)
    platform.plot(
x='user_score',
y='sales',
kind='scatter',
alpha=0.4,
title=row,
xlabel='Оценка пользователей',
ylabel='Сумма продаж'
            )

"""x360, ps4, xone, wiiu, wii - самые стабильно прибыльные за период с 2013 по 2016 гг."""

for row in data_future['platform'].unique():
    platform = data_future[data_future['platform']==row]
    platform = platform[platform['platform'].isin(['X360', 'PS4', 'XOne', 'WiiU', 'Wii'])]
    if not platform.empty:
        platform.plot(
x='critic_score',
y='sales',
kind='scatter',
alpha=0.4,
title=row,
xlabel='Оценка критиков',
ylabel='Сумма продаж'
            )

for row in data_future['platform'].unique():
    platform = data_future[data_future['platform']==row]
    platform = platform[platform['user_score']!='tbd']
    platform = platform[platform['user_score']!='nan']
    platform['user_score'] = platform['user_score'].astype(float)
    platform = platform[platform['platform'].isin(['X360', 'PS4', 'XOne', 'WiiU', 'Wii'])]
    if not platform.empty:
        platform.plot(
x='user_score',
y='sales',
kind='scatter',
alpha=0.4,
title=row,
xlabel='Оценка пользователей',
ylabel='Сумма продаж'
            )

data.groupby('genre')['sales'].sum().plot(kind='bar',
figsize=(10, 6),
title='Распределение суммы продаж по жанрам',
xlabel='Жанр',
ylabel='Сумма продаж'
     )

plt.figure(figsize=(13, 8))
sns.boxplot(data=data_future, y='sales', x='genre')

plt.title('Продажи по перспективным платформам')
plt.xlabel('Платформы')
plt.ylabel('Общие продажи')
plt.ylim(0, 3)

plt.show()

"""Говоря о жанрах - лидерами стабильных продаж стали игры со стрельбой, спортивные и игры, где нужно строить, самыми отстающими по продажам стали игры про путешествия.

### Мини-вывод:

- Изучили кол-во игр, которые были выпущены в разные годы. Определили актуальный период 2013-2016гг.

- Выделили суммарно самые продажные платфвормы - 'DS', 'PS2', 'PS3', 'Wii', 'X360'. Построили распределения по годам и графики для лучшего понимания.

- За 4-6 лет примерно появляются новые и исчезают старые платформы.

- Предположили возможный прогноз 2017 гг.

- Потенциально прибыльными платформами на 2017 можно выделить - XOne и PS4.

- Построили график "ящик с усами".

- Оценили, что отзывы пользователей и критиков не сильно влияют на продажи внутри одной крупной платформы PS2, но эта платформа уже "затухающая". Проверка же более перспективных платформ показала, что рейтинг критиков влияет на продажи чуть сильнее, чем отзывы пользователей.

- Самым прибыльным жанром выделяют экшн-игры, misc - простые и спортивные, а самыми низкими продажами обладают - стратегии, но это если сравнивать их по общей выручке. Самыми стабильными по прибыли же мы выделили platform, sports и shooter, самыми отстающими по продажам стали игры про путешествия.

## Портрет пользователя каждого региона

### Портрет пользователя Северной Америки
"""

data_future['rating'].fillna('unknown')

data_future.groupby('platform')['na_sales'].sum().reset_index().sort_values(by='na_sales', ascending=False).head()

data_future.groupby('genre')['na_sales'].sum().reset_index().sort_values(by='na_sales', ascending=False).head()

data_future.groupby('rating')['na_sales'].sum().reset_index().sort_values(by='na_sales', ascending=False).head()

data_future.groupby('rating')['na_sales'].sum().plot(kind='bar',
figsize=(6, 6),
title='Распределение количества продаж по рейтингу NORTH AMERICA',
xlabel='Рейтинг ESRB',
ylabel='Количество продаж'
     )

"""Северный американец - любитель экшн-игр,стрелковых,спортивных игр, ролевых и простых.

Платформы - PS4, XOne, X360, PS3, 3DS

Популярны игры для взрослых, для всех, игры 10+ и для подростков,.

### Портрет пользователя Европы
"""

data_future.groupby('platform')['eu_sales'].sum().reset_index().sort_values(by='eu_sales', ascending=False).head()

data_future.groupby('genre')['eu_sales'].sum().reset_index().sort_values(by='eu_sales', ascending=False).head()

data_future.groupby('rating')['eu_sales'].sum().reset_index().sort_values(by='eu_sales', ascending=False).head()

data_future.groupby('rating')['eu_sales'].sum().plot(kind='bar',
figsize=(6, 6),
title='Распределение количества продаж по рейтингу EUROPE',
xlabel='Рейтинг ESRB',
ylabel='Количество продаж'
     )

"""Платформы: PS4, PS3, XOne, X360, 3DS

Европейцы - любители экшн-игр, стрелковых, спортивных, ролевых игр и гонок.

Популярны игры для взрослых, для всех, для подростков и игры 10+.

### Портрет пользователя Японии
"""

data_future.groupby('platform')['jp_sales'].sum().reset_index().sort_values(by='jp_sales', ascending=False).head()

data_future.groupby('genre')['jp_sales'].sum().reset_index().sort_values(by='jp_sales', ascending=False).head()

data_future.groupby('rating')['jp_sales'].sum().reset_index().sort_values(by='jp_sales', ascending=False).head()

data_future.groupby('rating')['jp_sales'].sum().plot(kind='bar',
figsize=(6, 6),
title='Распределение количества продаж по рейтингу JAPAN',
xlabel='Рейтинг ESRB',
ylabel='Количество продаж'
     )

"""Платформы: 3DS, PS3, PSV, PS4, WiiU

Ролевые, экшн, простые, игры с борьбой и спортивные игры.

Популярны игры для подростков, для всех, для взрослых, и игры 10+.

### Вывод:

Самыми популярными в этих регионах являются экшн-игры, ролевые и спортивные.

Рейтинг ESRB влияет на продажи в этих регионах - самыми популярными остаются игры для всех, без возратсных ограничений.

Проставила значение 'unknown' вместо пропущенных значений - получилось, что в каждой стране достаточно большое кол-во игр осталось без рейтинга. Больше всего игр без рейтинга продаются в Японии, из чего можно сделать вывод, что рейтинг как раз используется по большей части Западом.

## Проверка гипотез

### Сравнение платформ Xbox One и PC
**Нулева гипотеза:** Средние пользовательские рейтинги платформ Xbox One и PC равны

**Альтернативаня гипотеза:** Средние пользовательские рейтинги платформ Xbox One и PC не равны
"""

game_new = data.query('year_of_release >= 2013').copy()
game_new = game_new.dropna(subset=['user_score'])
results = st.ttest_ind(
    game_new.query('platform == "XOne"')['user_score'],
    game_new.query('platform == "PC"')['user_score'],
    equal_var=False)

alpha = 0.05
print('p-значение:', results.pvalue)

if results.pvalue < alpha:
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

"""Принимаем как нуевую гипотезу что Xbox One = PC, как двустороннюю гипотезу. По формулировке гипотезы нужно узнать любое отклонение от равенства. Поэтому альтернативная гипотеза закоючается в неравенстве двух платформ.

### Сравнение жанров
**Нулевая гипотеза:** Средние пользовательские рейтинги жанров Action и Sports равны

**Альтернативная гипотеза:** Средние пользовательские рейтинги жанров Action и Sports не равны
"""

alpha = 0.05
action = data_future[data_future['genre']=='Action']['user_score'].dropna()
sports = data_future[data_future['genre']=='Sports']['user_score'].dropna()

result_two = st.ttest_ind(action, sports)
result_two

if result_two.pvalue<alpha:
    print('Отвергаем гипотезу')
else:
    print('Не отвергаем гипотезу')

action.mean()

sports.mean()

"""Почти то же самое делаем с этой гипотезой, но приравниваем жанры Action и Sports

## Общий вывод

Наш исследуемый датафрейм - data. По общей информации можно увидеть, что данных в датафрейме достаточно много, строк > 16 тысяч.

В данных 11 столбцов с названием, платформой, годом выпуска, жанром, продажам в Северной Америке, Европе, Японии и других регионах, оценку критиков, пользователей и рейтига ESRB (англ. Entertainment Software Rating Board).

Заменяли названия столбцов на строчные, преобразовывали данные в необходимый тип, удаляли и заполняли пропуски, часть пропусков оставляли, так как их было очень много.

Посчитали суммарные продажи и выяснили что значит 'tbd', изучили кол-во игр, которые были выпущены в разные годы, определили актуальный период 2013-2016гг.

Выделили суммарно самые продажные платформы - 'DS', 'PS2', 'PS3', 'Wii', 'X360'. Построили распределения по годам и графики для лучшего понимания.

Предположили возможный прогноз 2017 гг и возможный период времени за который появляются новые платформы и исчезают старые(4-6 лет).

X360, PS3, GB, PS - самые стабильно прибыльные за весь период исследования. А X360, PS4 и XOne - самые стабильно прибыльные за период 2013-2016 годы.

Потенциально прибыльными платформами на 2017 можно выделить - XOne и PS4.

Построили график "ящик с усами".

Оценили, что отзывы пользователей и критиков не сильно влияют на продажи внутри одной крупной платформы PS2, но на этом исследования не закончились. Важно учитывать, что чем более современные платформы мы рассматривали - тем больше проявлялась зависимость к оценке игр критиками. Оценки пользователей тоже влияют на продажи, но немного меньше.

Самым прибыльным жанром выделяют экшн-игры, misc - простые и спортивные, а самыми низкими продажами обладают - стратегии, но есть опредленные ньюансы, не все из этих жанров действительно стабильно прибыльные.

Самыми стабильными по прибыли мы определили platform, sports и shooter, самыми отстающими по продажам стали игры про путешествия.

Рейтинг ESRB влияет на продажи в этих регионах - самыми популярными остаются игры для всех, без возрастных ограничений, особенность рейтинга - он используется по большей части западными странами.

В разных регионах выделяются разные приоритеты к разным жанрам.

Используем t-критерий Стьюдента для независимых выборок.

По итогам исследования можно сделать вывод о платформах, на которые следует обратить внимание - это ХOne и PS4.

Успешность игры можно оценить по следующим пунктам - это экшн, спортивная или ролевая игры, с рейтингом без ограничений, будет здорово, если у игры хорошие оценки от критиков и пользователей.
"""