# -*- coding: utf-8 -*-
"""Проект по выбору локации

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpEhbryxNgKcQab_T5UV5lNNroQtI2ST

# Проект по выбору локации
**Описание проекта:** в добывающей компании «...» необходимо решить, где бурить новую скважину.

**Цель:** Разработать модель машинного обучения, которая поможет определить регион, где добыча принесёт наибольшую прибыль.

**Ход исследования:**
- В избранном регионе ищут месторождения, для каждого определяют значения признаков;

- Строят модель и оценивают объём запасов;

- Выбирают месторождения с самым высокими оценками значений. Количество месторождений зависит от бюджета компании и стоимости разработки одной скважины;

- Прибыль равна суммарной прибыли отобранных месторождений.

**Общий вывод:** резюмирование полученных результатов, формулировка ключевых выводов и рекомендаций.

С помощью данного исследования мы стремимся построить надёжную модель машинного обучения, которая сможет точно предсказывать объём запасов нефти по имеющимся геологическим признакам и определить наиболее перспективный регион для разработки скважин. Решение задачи **регрессии** с помощью метрик **RMSE** - измеряет среднюю ошибку и средний предсказанный запас.
"""

from google.colab import files
uploaded = files.upload()

"""## Загрузка и подготовка данных
### Импорт библиотек
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler
from sklearn.metrics import mean_squared_error

RANDOM_STATE = 42
TEST_SIZE = 0.25

"""### Загрузка данных"""

geo_data_0 = pd.read_csv('geo_data_0.csv')
geo_data_1 = pd.read_csv('geo_data_1.csv')
geo_data_2 = pd.read_csv('geo_data_2.csv')

"""### Функция анализа данных"""

def analysis_df (data):
    data.info()
    display(data.isna().sum())
    display(data.duplicated().sum())
    display(data.head(10))
    display(data.shape)

analysis_df(geo_data_0)

analysis_df(geo_data_1)

analysis_df(geo_data_2)

"""### Вывод

Импортированы иблиотеки, данные загружены, изучены с помощью функции. geo_data_0, geo_data_1, geo_data_2 - в каждом из созданных датафреймов 100 тысяч строк, 5 столбцов, нет явных дубликатов, нет пропусков, типы данных совпадают. Данные в идеальном состоянии на первый взгляд.

## Обучение и проверка модели
### Обучение модели
"""

region_df = {
    0: geo_data_0,
    1: geo_data_1,
    2: geo_data_2
}

y_valids = {}
predictions_all = {}

for region, df in region_df.items():
    print('Регион', region)

    X = df.drop(columns=['product', 'id'])
    y = df['product']

    X_train, X_valid, y_train, y_valid = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE
    )

    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_valid)

    results = pd.DataFrame({
        'actual': y_valid.values,
        'predicted': predictions
    })
    y_valids[region] = y_valid.reset_index(drop=True)
    predictions_all[region] = predictions
    mean_pred = predictions.mean()
    rmse = np.sqrt(mean_squared_error(y_valid, predictions))

    print('Средний предсказанный запас:', round(mean_pred, 2))
    print('RMSE модели:', round(rmse, 2))

"""### Вывод

Обучаем линейную модель по условию задачи. Наш целевой признак - product — объём запасов в скважине (тыс. баррелей).

Для избежания ошибки исключаем из выборки и признак 'id'. Сохраняе предсказания на валидационной выборке и узнаем средний запас в скважине по регионам.

По данным видим, что меньше всего запасов у Региона 1, однако по метрике RMSE правильнее всего модель предсказывает Регион 1, из чего можно сделать вывод о том, что разница 0 и 2 региона с 1, возможно, ошибочна.

## Подготовка к расчёту прибыли
### Ввод данных
"""

point_all = 500 # При разведке региона исследуют 500 точек

point_best = 200 # 200 лучших точек для разработки

money_bar = 450 # один баррель сырья приносит 450 рублей дохода

money_prod = 450000 # Доход с каждой единицы продукта составляет 450 тыс. рублей

money_all = 10000000000 # Бюджет на разработку скважин в регионе — 10 млрд рублей.

losses = 2.5 # вероятность убытков меньше 2.5

volume_all = money_all/(point_all*money_bar) # минимальный объем без рисков

volume_best = money_all/(point_best*money_bar)

print(round(volume_all, 2))
print(round(volume_best, 2))

#Значения в тысячах баррелей:
mean_region_0 = geo_data_0['product'].mean()
mean_region_1 = geo_data_1['product'].mean()
mean_region_2 = geo_data_2['product'].mean()

round(mean_region_0, 2)

round(mean_region_1, 2)

round(mean_region_2, 2)

"""### Вывод

Каждый из предоставленных регионов проходит под ограничения в объеме, если исходить из расчетов, что 500 точек будут работать.

Но, насколько я поняла, нужно их исключить и оставить 200, тогда ни один из регионов (по средним значениям) не даст компании прибыль, а лишь ухудшит положение дел. Все значения меньше 111 тысяч баррелей на скважину.

## Расчёт прибыли и рисков
### Функция для расчета прибыли
"""

def profit_an(target, predictions, point_best=point_best, money_bar=money_bar):
    pred_series = pd.Series(predictions)
    top_predictions = pred_series.sort_values(ascending=False).head(point_best)
    selected_ind = top_predictions.index
    selected_target = target.iloc[selected_ind]

    total_volume = selected_target.sum()
    profit = total_volume * money_bar

    return profit

result = round(profit_an(y_train, predictions, point_best=point_best, money_bar=money_bar), 2)

result

result/450000

"""### Вывод

Написала функцию для расчёта прибыли по выбранным скважинам и предсказаниям модели.

8,527,024.01 - прибыль для полученного объёма сырья.

18.95 - тысяч баррелей(сырья)

## Техника Bootstrap
### Поиск распределения прибыли
"""

def bootstrap_analysis(target, predictions, n_iterations=1000, point_best=point_best, money_prod=money_prod, money_all=money_all):
    profits = []

    for m in range(n_iterations):
        ind = np.random.choice(target.index, size=point_all, replace=True)
        sample_target = target.loc[ind].reset_index(drop=True)
        sample_predictions = pd.Series(predictions[ind]).reset_index(drop=True)

        profit = profit_an(sample_target, sample_predictions, point_best, money_prod)
        no_profit = profit - money_all
        profits.append(no_profit)

    profits = pd.Series(profits)

    mean_profit = profits.mean()
    lower = profits.quantile(0.025)
    upper = profits.quantile(0.975)
    risk = (profits < 0).mean()

    return mean_profit, lower, upper, risk

"""### Результаты"""

results = {}

for region in range(3):
    y_valid = y_valids[region]
    preds = predictions_all[region]

    mean_profit, lower, upper, risk = bootstrap_analysis(y_valid, preds)

    results[region] = {
        'mean_profit': mean_profit,
        '95% interval': (lower, upper),
        'risk': risk
    }

    print('\nРегион {}'.format(region))
    print('  Средняя прибыль: {:,.0f} руб.'.format(mean_profit))
    print('  95% доверительный интервал: ({:,.0f}, {:,.0f}) руб.'.format(lower, upper))
    print('  Риск убытков: {:.2%}'.format(risk))

"""### Вывод

Посчитали риски и прибыль для каждого региона: Регион 1 является наиболее безопасным. Риск составляет лишь ~ 1.3%
    
Применили технику Bootstrap с 1000 выборок.Нашли среднюю прибыль, 95%-й доверительный интервал и риск убытков.

Для развития компании следует присмотреться к Региону 1 - его средняя прибыль наибольшая, риск убытков - самый минимальный из всех субъектов.

## Вывод

В рамках проекта для компании «...» была построена модель машинного обучения(линейная), предсказывающая объём запасов нефти в трёх регионах на основе геологических признаков. Основная цель — определить регион, в котором разработка скважин даст наибольшую прибыль при допустимом уровне риска.

Для каждого региона:

Построена модель линейной регрессии;
Проведена валидация качества модели (средний запас, RMSE);
Проведён анализ прибыли с использованием техники Bootstrap на 1000 итераций;
Оценены риски и рассчитаны доверительные интервалы прибыли.


Регион 1 демонстрирует наивысшую среднюю прибыль и минимальный риск убытков по результатам анализа. Он соответствует всем критериям: прибыльность, устойчивость предсказаний и безопасность инвестиций.
"""