# -*- coding: utf-8 -*-
"""Проект: Линейные модели в машинном обучении

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMVkfvXW9aMVxHwrOq0SQqX2NaUHSyh1

# Проект: Линейные модели в машинном обучении #
***
**Описание проекта:** Молочное производство — стабильный и прибыльный бизнес, но его успех зависит от качества стада. Используя данные о стаде фермера на текущий момент, об имени папы каждой коровы в стаде фермера и данные о коровах «...», которых фермер хочет изучить перед покупкой.

**Цель:** Разработать две модели машинного обучения для помощи фермеру в отборе коров, удовлетворяющих строгим критериям:

Прогнозирование удоя – модель предсказывает годовой надой (≥ 6000 кг).

Оценка вкуса молока – модель определяет вероятность, что молоко будет соответствовать вкусовым стандартам.

**Ход исследования:**
Шаг 1. Загрузка и изучение данных: загрузить датасеты и изучить структуру данных
Шаг 2. Предобработка данных: обработка пропусков
Шаг 3. Исследовательский анализ данных: статистический анализ всех признаков и построение графиков
Шаг 4. Корреляционный анализ признаков в датасете "ferma_main.csv": изучение взаимосвязи между признаками
Шаг 5. Задача регрессии: обучение трех моделей простой линейной регрессии
Шаг 6. Задача классификации: обучение модели
Шаг 7. Итоговые выводы

**Общий вывод:** резюмирование полученных результатов, формулировка ключевых выводов и рекомендаций.

С помощью данного исследования мы стремимся дать всесторонний анализ коров для удоя, что станет началом для дальнейшего расширения бизнеса фермера.

## 1 шаг. Загрузка данных

### 1.1 Импортируем библиотеки и создаем датафреймы для работы
"""

from google.colab import files
uploaded = files.upload()

!pip install --upgrade scikit-learn
!pip install phik q

import phik
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy import stats as st
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

plt.rcParams["figure.figsize"] = (7,7)
RANDOM_STATE = 42

ferma_main = pd.read_csv('ferma_main.csv', sep=';', decimal ='.')
ferma_dad = pd.read_csv('ferma_dad.csv', sep=';', decimal ='.')
cow_buy = pd.read_csv('cow_buy.csv', sep=';', decimal ='.')

"""### 1.2 Создаем функцию для изучения каждого датафрейма"""

def analysis_df (data):
    data.info()
    display(data.isna().sum())
    display(data.duplicated().sum())

analysis_df(ferma_main)

analysis_df(ferma_dad)

analysis_df(cow_buy)

ferma_main.head()

ferma_dad.head()

cow_buy.head()

"""### 1.3 Вывод

ferma_main, ferma_dad и cow_buy - исследуемые датафреймы.
По общей информации можно увидеть, что есть дубликаты, а пропущенных значеий нет, также необходимо будет изменить тип данных в некоторых столбцах и удалить дубликаты.

Строк в датафреймах не очень много, самый большое дф ferma_main с 634 строками.

В первом дф 12 столбцов с различными характеристиками коров и их молока, во втором 2, в третьем 7 столбцов.

Необходимо исправить название столбцов, посмотреть и изменить типы данных в некоторых столбцах.

##  2 шаг. Предобработка данных

### 2.1 Проверяем данные на наличие пропусков и дубликатов
"""

ferma_main.duplicated().sum()

ferma_main = ferma_main.drop_duplicates()

cow_buy.duplicated().sum()

ferma_main.duplicated().sum()

ferma_main['Удой, кг'].nunique()

ferma_main['Жирность,%'].nunique()

ferma_main['Сырой протеин, г'].nunique()

cow_buy.duplicated().sum()

"""### 2.2 Проверка на наличие пропусков"""

ferma_main.isna().sum()

cow_buy.isna().sum()

"""### 2.3 Преобразование типов данных"""

ferma_main.info()

ferma_main['СПО (Сахаро-протеиновое соотношение)'] = ferma_main['СПО (Сахаро-протеиновое соотношение)'].str.replace(',', '.').astype(float)
ferma_main['ЭКЕ (Энергетическая кормовая единица)'] = ferma_main['ЭКЕ (Энергетическая кормовая единица)'].str.replace(',', '.').astype(float)
ferma_main['Жирность,%'] = ferma_main['Жирность,%'].str.replace(',', '.').astype(float)
ferma_main['Белок,%'] = ferma_main['Белок,%'].str.replace(',', '.').astype(float)

ferma_main.head()

ferma_main.info()

"""### 2.4 Вывод

- Удалили строки-дубликаты

- Проверили наличие пропусков

- Подготовили данные для дальнейшей работы

- Преобразовали данные в необходимый тип, для этого заменили "," на "."

## 3 шаг. Исследовательский анализ данных
"""

ferma_main.columns = ferma_main.columns.str.lower()

ferma_dad.columns = ferma_dad.columns.str.lower()

cow_buy.columns = cow_buy.columns.str.lower()

"""### 3.1 Построение графиков для категориальных признаков"""

ferma_main.groupby('порода')['id'].count().plot(
kind='bar',
xlabel='Название породы',
ylabel='Количество коров',
title='Породы коров'
);

"""Коров породы "Вис Бик Айдиал" больше чем РефлешнСоверинг."""

ferma_main.groupby('тип пастбища')['id'].count().plot(
kind='bar',
xlabel='Тип пастбища',
ylabel='Количество коров',
title='Тип пастбища для коровы'
);

"""Большинство коров живут на холмистом пастбище"""

ferma_main['тип пастбища'] = ferma_main['тип пастбища'].replace('Равнинные', 'Равнинное')

ferma_main.groupby('тип пастбища')['id'].count().plot(
kind='bar',
xlabel='Тип пастбища',
ylabel='Количество коров',
title='Тип пастбища для коровы'
);

ferma_main.groupby('порода папы_быка')['id'].count().plot(
kind='bar',
xlabel='Порода папы быка',
ylabel='Количество коров',
title='Порода папы быка коровы'
);

"""Здесь мы видим одну и ту же породу, которая растянулась на дво столбца, необходимо переименовать и перепроверить заново."""

ferma_main['порода папы_быка'] = ferma_main['порода папы_быка'].replace('Айдиал', 'Айдиалл')

ferma_main.groupby('порода папы_быка')['id'].count().plot(
kind='bar',
xlabel='Порода папы быка',
ylabel='Количество коров',
title='Порода папы быка коровы'
);

"""После редактирования мы видим, что породы пап-быков практически равны."""

ferma_main.groupby('вкус молока')['id'].count().plot(
kind='bar',
xlabel='Вкус молока',
ylabel='Количество коров',
title='Вкус молока коровы'
);

"""Большинство коров дают вкусное молоко"""

ferma_main.groupby('возраст')['id'].count().plot(
kind='bar',
xlabel='Возраст',
ylabel='Количество коров',
title='Возраст коров'
);

"""Большинство коров живут уже более 2 лет

### 3.2 Построение графиков для количественных признаков
"""

columns = ['удой, кг', 'эке (энергетическая кормовая единица)', 'сырой протеин, г', 'спо (сахаро-протеиновое соотношение)', 'жирность,%', 'белок,%']

ferma_main['удой, кг'].plot(kind='hist',
bins=10)
plt.title('Распределение удоя по коровам')
plt.xlabel('Удой, кг')
plt.ylabel('Количество коров')
plt.grid(True)

plt.boxplot(ferma_main['удой, кг'])
plt.title('Боксплот удоя по коровам')
plt.xlabel('Удой, кг')
plt.grid(True)
plt.show()

ferma_main['удой, кг'].describe()

"""Изучаем максимальные и минимальные значения, делаем вывод по графику и выведенной таблице о том, что выше 7300 скорее всего нереальные значения, выбросы. Принимаем решение сразу ибавиться от таких значений."""

ferma_dad[ferma_dad['id']==17]

ferma_main[ferma_main['id']==17]

ferma_main = ferma_main[ferma_main['удой, кг']<7300]

plt.boxplot(ferma_main['удой, кг'])
plt.title('Боксплот удоя по коровам')
plt.xlabel('Удой, кг')
plt.grid(True)
plt.show()

ferma_main['эке (энергетическая кормовая единица)'].plot(kind='hist',
bins=30)
plt.title('Показатель питательности корма')
plt.xlabel('ЭКЕ')
plt.ylabel('Количество коров')
plt.grid(True)

plt.boxplot(ferma_main['эке (энергетическая кормовая единица)'])
plt.title('Боксплот ЭКЕ по коровам')
plt.xlabel('ЭКЕ')
plt.grid(True)
plt.show()

ferma_main['эке (энергетическая кормовая единица)'].describe()

ferma_main['сырой протеин, г'].plot(kind='hist',
bins=30)
plt.title('Cодержание сырого протеина в корме ')
plt.xlabel('Сырой протеин')
plt.ylabel('Количество коров')
plt.grid(True)

plt.boxplot(ferma_main['сырой протеин, г'])
plt.title('Боксплот сырого протеина по коровам')
plt.xlabel('Сырой протеин')
plt.grid(True)
plt.show()

ferma_main['сырой протеин, г'].describe()

ferma_main['спо (сахаро-протеиновое соотношение)'].plot(kind='hist',
bins=10)
plt.title('Отношение сахара к протеину в корме коровы.')
plt.xlabel('СПО')
plt.ylabel('Количество коров')
plt.grid(True)

plt.boxplot(ferma_main['спо (сахаро-протеиновое соотношение)'])
plt.title('Боксплот СПО по коровам')
plt.xlabel('СПО')
plt.grid(True)
plt.show()

ferma_main['спо (сахаро-протеиновое соотношение)'].describe()

ferma_main['жирность,%'].plot(kind='hist',
bins=30)
plt.title('Cодержание жиров в молоке')
plt.xlabel('Жирность,%')
plt.ylabel('Количество коров')
plt.grid(True)

plt.boxplot(ferma_main['жирность,%'])
plt.title('Боксплот жирности молока по коровам')
plt.xlabel('Жирность')
plt.grid(True)
plt.show()

ferma_main['жирность,%'].describe()

ferma_main['белок,%'].plot(kind='hist',
bins=10)
plt.title('Cодержание белков в молоке')
plt.xlabel('Белок,%')
plt.ylabel('Количество коров')
plt.grid(True)

plt.boxplot(ferma_main['белок,%'])
plt.title('Боксплот белка молока по коровам')
plt.xlabel('Белок')
plt.grid(True)
plt.show()

ferma_main['белок,%'].describe()

ferma_main.info()

ferma_dad.groupby('имя папы')['id'].count().plot(
kind='bar',
xlabel='Имя Папы',
ylabel='Количество коров',
title='Имя папы-быка'
);

cow_buy['порода'].value_counts().plot(
kind='bar',
xlabel='Порода',
ylabel='Количество коров',
title='Породы коров'
);

cow_buy['тип пастбища'].value_counts().plot(
kind='bar',
xlabel='Тип пастбища',
ylabel='Количество коров',
title='Тип пастбища'
);

cow_buy['порода папы_быка'].value_counts().plot(
kind='bar',
xlabel='порода папы_быка',
ylabel='Количество коров',
title='порода папы_быка'
);

cow_buy['имя_папы'].value_counts().plot(
kind='bar',
xlabel='Имя_папы',
ylabel='Количество коров',
title='Имя_папы'
);

cow_buy['возраст'].value_counts().plot(
kind='bar',
xlabel='Возраст',
ylabel='Количество коров',
title='Возраст'
);

cow_buy['текущая_жирность,%'] = cow_buy['текущая_жирность,%'].str.replace(',', '.').astype(float)
cow_buy['текущий_уровень_белок,%'] = cow_buy['текущий_уровень_белок,%'].str.replace(',', '.').astype(float)

cow_buy['текущий_уровень_белок,%'].plot(kind='hist',
bins=10)
plt.title('Cодержание белков в молоке')
plt.xlabel('Текущий_уровень_белок,%')
plt.ylabel('Количество коров')
plt.grid(True)

plt.boxplot(cow_buy['текущий_уровень_белок,%'])
plt.title('Боксплот белка молока по коровам')
plt.xlabel('Белок')
plt.grid(True)
plt.show()

cow_buy['текущий_уровень_белок,%'].describe()

cow_buy['текущая_жирность,%'].plot(kind='hist',
bins=10)
plt.title('Cодержание жиров в молоке')
plt.xlabel('Текущая_жирность,%')
plt.ylabel('Количество коров')
plt.grid(True)

plt.boxplot(cow_buy['текущая_жирность,%'])
plt.title('Боксплот жирности молока по коровам')
plt.xlabel('Жирность')
plt.grid(True)
plt.show()

cow_buy['текущая_жирность,%'].describe()

"""### 3.4 Вывод
- Изучили данные более подробно, составили графики для категориальных признаков и гистограммы для количественных признаков.
- По графикам видно: Коров породы "Вис Бик Айдиал" больше чем РефлешнСоверинг, большинство коров живут на холмистом пастбище, породы пап-быков практически равны, молоко у большиснвта коров вкусное, а живут почти все уже больше 2 лет.
- В некоторых количественных переменных были выбросы, из-за чего пришлось немного уменьшить ДФ, но не критично, убрали всего 1 строку с завышенным значением.
- Дополнительно изменила тип данных в колчиественных признаках в ДФ cow_buy

## 4 Шаг.  Корреляционный анализ
"""

ferma_main.head()

id_column = ferma_main['id']
ferma_main = ferma_main.drop(columns=['id'])

interval_cols = [
    'удой, кг',
    'эке (энергетическая кормовая единица)',
    'сырой протеин, г',
    'спо (сахаро-протеиновое соотношение)',
    'жирность,%',
    'белок,%'
]


corr_new = ferma_main.phik_matrix(interval_cols=interval_cols)

plt.figure(figsize=(10, 8))
sns.heatmap(corr_new, annot=True, cmap='coolwarm')
plt.title('Correlation')
plt.show()

"""### 4.1 Расчет коэффициентов корреляции между всеми признаками"""

ferma_main_corr = ferma_main.select_dtypes(include=['number']).corr(method='kendall')

sns.heatmap(ferma_main_corr, annot=True)

ferma_main['id'] = id_column

"""Благодаря тепловой карте можно заметить яркую линейную связь между признаками: удой и СПО, удой и ЭКЕ, ЭКЕ и СПО, у остальных признаков зависимость меньше

### 4.2 Диаграммы рассеяния scatterplot для признака Удой, кг и всех количественных признаков с учётом значения категориальных признаков.
"""

def colored_scatter(data, x_row, y_row, color_row):
    for row in data[color_row].unique():
        row_data = data[data[color_row] == row]
        plt.scatter(row_data[x_row], row_data[y_row],
                   alpha=0.5,
                   label=row)

    plt.title(f'Зависимость {y_row} от {x_row} (по {color_row})')
    plt.xlabel(x_row)
    plt.ylabel(y_row)
    plt.legend()
    plt.grid(True, alpha=0.5)

"""#### Зависимость от породы"""

colored_scatter(ferma_main, 'удой, кг', 'сырой протеин, г', 'порода')

"""По графику видим, что чем больше удой - тем больше сырого протеина. Сильной разницы между породами не видно, и линейная зависимость не сильная"""

colored_scatter(ferma_main, 'удой, кг', 'жирность,%', 'порода')

"""По графику видно, что большинство коров породы РефлешнСоверинг дают ~ 3.7% молоко при большем удое, а коровы Вис Бик Айдиал 3.6% молоко при чуть меньшем удое"""

colored_scatter(ferma_main, 'удой, кг', 'эке (энергетическая кормовая единица)', 'порода')

"""На это графике мы уже видим сильную квадратичную связь - чем больше ЭКЕ - тем больше удой, независимо от породы"""

colored_scatter(ferma_main, 'удой, кг', 'спо (сахаро-протеиновое соотношение)', 'порода')

"""По этому графику можно сказать, что у большинства коров РефлешнСоверинг СПО молока больше при высоких показателях удоя, чем у коров Вис Бик Айдиал

Имеет смысл перевести в категорию
"""

colored_scatter(ferma_main, 'удой, кг', 'белок,%', 'порода')

"""По данному графику видно, что белок примерно одинаковый у всех пород, независимо от удоя, около 3%, но у РефлешнСоверинг он немного меньше, чем у Вис Бик айдиал

Подводя итог, можно сказать, что сильной разницы между породами нет, но

у большинства коров РефлешнСоверинг СПО молока больше при высоких показателях удоя, чем у коров Вис Бик Айдиал,

большинство коров породы РефлешнСоверинг дают ~ 3.7% молоко при большем удое, а коровы Вис Бик Айдиал 3.6% молоко при чуть меньшем удое,

у большинства коров Вис Бик Айдиал процентное содержание белка немного выше, чем у РефлешнСоверинг.

#### Зависимость от типа пастбища
"""

colored_scatter(ferma_main, 'удой, кг', 'белок,%', 'тип пастбища')

"""Линейной зависимости удоя и белка на разных типах пастбища не наблюдается, большинство коров живут на холмистом типе"""

colored_scatter(ferma_main, 'удой, кг', 'спо (сахаро-протеиновое соотношение)', 'тип пастбища')

"""Линейной зависимости удоя и СПО на разных типах пастбища не наблюдается

Имеет смысл перевести в категорию
"""

colored_scatter(ferma_main, 'удой, кг', 'эке (энергетическая кормовая единица)', 'тип пастбища')

"""На это графике видно сильную квадратичную связь, чем больше ЭКЕ - тем боьше ЭКЕ на любом типа пастбища."""

colored_scatter(ferma_main, 'удой, кг', 'жирность,%', 'тип пастбища')

"""На графике видна небольшая зависимость - чем больше удоя - тем больше Жирность молока, независимо от типа пастбища"""

colored_scatter(ferma_main, 'удой, кг', 'сырой протеин, г', 'тип пастбища')

"""Тоже имеется небольшая линейная зависимость, чем больше удоя, тем больше сырого протиена, независимо от типа пастбища
Подводя итог о пастбищах можно сделать вывод о том, что сильных различий показателей на разных типах пастбищ - нет, а большинство коров живут на холмах.

#### Зависимость от породы папы-быка
"""

colored_scatter(ferma_main, 'удой, кг', 'сырой протеин, г', 'порода папы_быка')

"""Есть небольшая линейная зависимость, чем больше удой, тем больше сырого протеина, если у коров папа-бык был Айдиалл, то удоя у них чуть больше"""

colored_scatter(ferma_main, 'удой, кг', 'жирность,%', 'порода папы_быка')

"""На этом графике видно небольшую линейную зависимость уоя и жинрости, у коров чей отец Айдиалл удой заметно выше"""

colored_scatter(ferma_main, 'удой, кг', 'эке (энергетическая кормовая единица)', 'порода папы_быка')

"""На этом графике также видим линейную зависимость удоя от ЭКЕ,  причем коровы, чей отец был Айдиалл опять лидируют."""

colored_scatter(ferma_main, 'удой, кг', 'спо (сахаро-протеиновое соотношение)', 'порода папы_быка')

"""На этом графике видно зависимость, чем больше удой - тем больше СПО

Имеет смысл перевести в категорию
"""

colored_scatter(ferma_main, 'удой, кг', 'белок,%', 'порода папы_быка')

"""На графике не видно линейной зависимости белка и удоя, все породы пап-быков распределены более менее равномерно
По итогам графиков по породам пап-быков, можно сделать вывод о том, что буренки Айдиаллов дают больший удой, чем буренки породы Соверин

#### Зависимость от вкуса молока
"""

colored_scatter(ferma_main, 'удой, кг', 'сырой протеин, г', 'вкус молока')

colored_scatter(ferma_main, 'удой, кг', 'жирность,%', 'вкус молока')

colored_scatter(ferma_main, 'удой, кг', 'эке (энергетическая кормовая единица)', 'вкус молока')

"""Наблюдаем квадратичную связь"""

colored_scatter(ferma_main, 'удой, кг', 'спо (сахаро-протеиновое соотношение)', 'вкус молока')

"""Имеет смысл перевести в категорию"""

colored_scatter(ferma_main, 'удой, кг', 'белок,%', 'вкус молока')

"""Зависимоти от вкуса молока совпадает с предудщими, ярких отличий вкусного и невкусного молока нет. Можно лишь сказать о том, что вкусного молока больше, и удоя по нему тоже больше

#### Зависимость от возраста
"""

colored_scatter(ferma_main, 'удой, кг', 'сырой протеин, г', 'возраст')

"""На графике видим линейную зависимость между Сырым протеином и удоем. Также необходимо заметить, что коровы возрастом меньше двух лет дают меньше молока."""

colored_scatter(ferma_main, 'удой, кг', 'жирность,%', 'возраст')

"""На графике видим зависимость, чем больше удоя, тем больше жирность. Также коровы до 2 лет дают молоко  в большиснтве случаев до 3.6%"""

colored_scatter(ferma_main, 'удой, кг', 'эке (энергетическая кормовая единица)', 'возраст')

"""Наблюдаем квадратичную связь"""

colored_scatter(ferma_main, 'удой, кг', 'спо (сахаро-протеиновое соотношение)', 'возраст')

"""Имеет смысл перевести в категорию"""

colored_scatter(ferma_main, 'удой, кг', 'белок,%', 'возраст')

"""По итогам графиков видно6 что коровы, возраст которых меньше 2 лет, дают меньше молока, но не всегда уступают по его качеству коровам постарше.

### 4.3 Вывод

Подводя итог по всем графикам выше, можно скзать о том, что существуею линейная связь между признаками: сильная: Удоя и ЭКЕ, Удой и СПО; слабее: Удой и и Сырой протеин, Удой и Жирность.

Если говорить о той же зависимость, но при разны категориальных признаках, то нужно сказать о том, что:

- порода РефлешнСоверинг дает большее кол-ва молока, и в большинстве случаев с олее выоскими показателями

- большинство коров живут на холмистом пастбище, нпоэтоум можем сделать вывод, что данное пастбище хорошо влияет на коров

- если у коровы папа-бык Айдиалл, то переживать не о чем, в большиснвте случаев показатели у них выше, чем  у остальных.

- вкус молока конечно играет роль, но в зависимостях не дал значимых результатов, можно сказать, что вкусного молоа немного больше, что говорит о большем удое

- коровы меньше 2 лет дают меньше молока, чем коровы старше 2 лет, но почти все показатели практически не отличаются от взрослых буренок.

## 5 Шаг  Задача регрессии

### 5.1 Обучение модели линейной регрессии

#### Первая модель
Сразу разеберем признаки в нашем датафрейме: исключаем то, что не может влиять на количество удоя, это признаки молока, то есть жирность, белок и вкус молока.

Целевой признак - Удой, кг.

Также разделяем признаки на количественные и категориальные.

Разбиваем на тренировочную и тестовую выборки.
"""

cat_col_names = ['эке (энергетическая кормовая единица)', 'сырой протеин, г', 'спо (сахаро-протеиновое соотношение)', 'порода', 'тип пастбища', 'порода папы_быка', 'возраст']

X = ferma_main[cat_col_names]
y = ferma_main['удой, кг']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    random_state=RANDOM_STATE
)


category = ['порода','тип пастбища', 'порода папы_быка', 'возраст']
numeric = ['эке (энергетическая кормовая единица)', 'сырой протеин, г', 'спо (сахаро-протеиновое соотношение)']

ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
scaler = StandardScaler()

X_train_ohe = ohe.fit_transform(X_train[category])
X_test_ohe = ohe.transform(X_test[category])

X_train_scaled = scaler.fit_transform(X_train.drop(columns=category))
X_test_scaled = scaler.transform(X_test.drop(columns=category))

X_train_processed = np.hstack([X_train_ohe, X_train_scaled])
X_test_processed = np.hstack([X_test_ohe, X_test_scaled])

X_train.shape[0]

X_train.shape[1]

X_train.shape

model = LinearRegression()
model.fit(X_train_processed, y_train)
y_pred_one = model.predict(X_test_processed)
r2_one = r2_score(y_test, y_pred_one)

"""Первая модель предсказывает не очень хорошо, ~22% ошибок."""

residuals_one = y_test - y_pred_one

residuals_one

plt.scatter(y_pred_one, residuals_one)
plt.title('Анализ дисперсии')
plt.xlabel('Предсказания модели')
plt.ylabel('Остатки')

plt.hist(residuals_one)
plt.title('Анализ остатков')
plt.xlabel('Остатки')
plt.ylabel('Количество остатков')

"""Первая модель показала себя не очень хорошо, 22% ошибок и рупорообразное распределние ошибок, которое свидетельствует о чередовании дисперсии

#### Вторая модель
"""

plt.scatter(data=ferma_main, x='спо (сахаро-протеиновое соотношение)', y='удой, кг', alpha=0.5)

plt.scatter(data=ferma_main, x='эке (энергетическая кормовая единица)', y='удой, кг', alpha=0.5)

ferma_main['новое спо'] = ferma_main['спо (сахаро-протеиновое соотношение)']>0.91
ferma_main['эке^2'] = ferma_main['эке (энергетическая кормовая единица)']**2

ferma_main.head()

col_names = ['сырой протеин, г', 'порода', 'тип пастбища', 'порода папы_быка', 'возраст', 'новое спо', 'эке^2', 'эке (энергетическая кормовая единица)', 'спо (сахаро-протеиновое соотношение)']
loc_name = ['удой, кг']

X = ferma_main[col_names]
y = ferma_main[loc_name]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    random_state=RANDOM_STATE
)

ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
scaler = StandardScaler()

category = ['порода','тип пастбища', 'порода папы_быка', 'возраст', 'новое спо']
numeric = ['сырой протеин, г', 'эке^2', 'спо (сахаро-протеиновое соотношение)', 'эке (энергетическая кормовая единица)']

X_train_ohe = ohe.fit_transform(X_train[category])
X_test_ohe = ohe.transform(X_test[category])

X_train_scaled = scaler.fit_transform(X_train.drop(columns=category))
X_test_scaled = scaler.transform(X_test.drop(columns=category))

X_train_processed = np.hstack([X_train_ohe, X_train_scaled])
X_test_processed = np.hstack([X_test_ohe, X_test_scaled])

"""Также задачу можно решить с помощью функции ниже:"""

def data_mo(X, y, category, numeric):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, random_state=RANDOM_STATE
    )

    ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
    scaler = StandardScaler()

    X_train_ohe = ohe.fit_transform(X_train[category])
    X_test_ohe = ohe.transform(X_test[category])

    X_train_scaled = scaler.fit_transform(X_train[numeric])
    X_test_scaled = scaler.transform(X_test[numeric])

    return X_train_ohe, X_test_ohe, X_train_scaled, X_test_scaled, y_train, y_test, ohe, scaler

data_mo(ferma_main[col_names], ferma_main[loc_name], category, numeric)

model_two = LinearRegression()
model_two.fit(X_train_processed, y_train)
y_pred_two = model_two.predict(X_test_processed)
r2_two = r2_score(y_test, y_pred_two)

r2_two

"""18% ошибок - уже лучше"""

residuals_two = y_test - y_pred_two

residuals_two

plt.scatter(y_pred_two, residuals_two)
plt.title('Анализ дисперсии')
plt.xlabel('Предсказания модели')
plt.ylabel('Остатки')

plt.hist(residuals_two)
plt.title('Анализ остатков')
plt.xlabel('Остатки')
plt.ylabel('Количество остатков')

"""По графику видно, что ошибки стали более равномерные с нормальной дисперсией остатков.

R2 увеличился на несколько пунктов.

Анализ остатков модели: дисперсия разброса ошибки стала чуть стабильнее на всём дипазане фактических данных. Это явное улучшение. Наблюдаются две зоны ошибок. Но разница дисперсии ошибок не систематическая, а выборочная.

Гистограма: среднее и медиана совпадают, но распределение не нормальное (бимодальности, плюс смещение среднего влево от нуля). Значит потенциал для улучшения модели всё ещё есть.

Общий вывод: Модель уже пригодна для прогнозирования.

#### Третья модель
"""

ferma_main.info()

ferma_dad.info()

ferma = ferma_main.merge(ferma_dad, on='id')

ferma.info()

ferma.head()

col = ['порода', 'тип пастбища', 'порода папы_быка', 'возраст', 'новое спо', 'имя папы', 'сырой протеин, г', 'эке^2', 'спо (сахаро-протеиновое соотношение)', 'эке (энергетическая кормовая единица)']
loc = ['удой, кг']
X = ferma[col]
y = ferma[loc]

category = ['порода', 'тип пастбища', 'порода папы_быка', 'возраст', 'новое спо', 'имя папы']
numeric = ['сырой протеин, г', 'эке^2', 'спо (сахаро-протеиновое соотношение)', 'эке (энергетическая кормовая единица)']


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    random_state=RANDOM_STATE
)

ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
scaler = StandardScaler()

ohe.fit(X_train[category])
scaler.fit(X_train[numeric])

X_train_ohe = ohe.transform(X_train[category])
X_test_ohe = ohe.transform(X_test[category])

X_train_scaled = scaler.transform(X_train[numeric])
X_test_scaled = scaler.transform(X_test[numeric])

X_train_processed = np.hstack([X_train_ohe, X_train_scaled])
X_test_processed = np.hstack([X_test_ohe, X_test_scaled])

model_three = LinearRegression()
model_three.fit(X_train_processed, y_train)
y_pred_three = model_three.predict(X_test_processed)
r2_three = r2_score(y_test, y_pred_three)

r2_three

"""17% ошибок"""

residuals_three = y_test - y_pred_three

residuals_three

plt.scatter(y_pred_three, residuals_three)
plt.title('Анализ дисперсии')
plt.xlabel('Предсказания модели')
plt.ylabel('Остатки')

plt.hist(residuals_three)
plt.title('Анализ остатков')
plt.xlabel('Остатки')
plt.ylabel('Количество остатков')

"""Вывод: Распределение остатков стало еще более равномерным, третья модель оказалась самой лучшей по результатам r2 для продолжения работы. Ошибок 17% - не идеально, модель будет ошибаться, но использовать ее уже можно.

Факторы на 82,8% объясняют разброс в целевой переменной. Это успех.

Анализ остатков модели: дисперсия разброса ошибки осталась стабильной. Есть около десятка "выдающихся" точек на высоких удоях, но это не системные дела, а разовая акция. Можем признать, что ошибка равномерная на всём диапазоне значений. Т.е. остатки - гомоскедастичны. Значит модель можно использовать для прогноза.

Гистограма: среднее и медиана совпадают, не смещены относительно 0. Но бимодальность присутствуют.

Общий вывод: Потенциал для улучшения модели всё ещё есть, но на текущий момент признаём модель качественной (остатки гомоскедастичны) и пригодной для работы. Посмотрим на точность модели.
"""

r2_one

r2_two

r2_three

"""### 5.2 Сравнение качеств модели по трём метрикам: MSE, MAE, RMSE"""

def comparison(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    rmse = mse**0.5
    return mse, mae, rmse

comparison(y_test, y_pred_one)

"""Рассмотрим первую модель -

MSE=43887, что говорит нам о том, что ошибки могли быть действительно большими,

MAE=164, модель ошибается в среднем на 164 кг удоя,

RMSE=209, модель иногда ошибается больше, чем на 164 кг, что плохо для МО
"""

comparison(y_test, y_pred_two)

"""Рассмотрим вторую модель -

MSE=37152, что говорит нам о том, что ошибки могли быть действительно большими, но этот результат уже лучше предыдущего,

MAE=151, модель ошибается в среднем на 151 кг удоя,

RMSE=192, модель иногда ошибается больше, чем на 151 кг, что плохо для МО, но выбросов в этой модели уже меньше.
"""

comparison(y_test, y_pred_three)

"""Рассмотрим третью модель -

MSE=34479, что говорит нам о том, что ошибки могли быть большими, но этот результат самый удачный,

MAE=145, модель ошибается в среднем на 145 кг удоя, что меньше всего из моделей

RMSE=185, модель иногда ошибается больше, чем на 145 кг, что плохо для МО, но выбросов в этой модели уже меньше.

Вывод: Самый минимальный разрыв в значениях MAE и RMSE получился у третьей модели, что говорит о наиболее удачном прогнозировании.

Самая минимальная метрика MSE тоже получилась у третьей модели. Дальше работа будет происходить именно по третьей модели, которая включает в себя большее количество признаков, чем у остальных.

### 5.3 Доверительный интервал
"""

lower_one = np.quantile(residuals_one, 0.025)
upper_one = np.quantile(residuals_one, 0.975)

lower_one

upper_one

"""В первой модели диапазон ошибки составляет от - 402 до 420"""

lower_two = np.quantile(residuals_two, 0.025)
upper_two = np.quantile(residuals_two, 0.975)

lower_two

upper_two

"""Во второй модели диапазон ошибки составляет от -385 до 390"""

lower_three = np.quantile(residuals_three, 0.025)
upper_three = np.quantile(residuals_three, 0.975)

lower_three

upper_three

"""В третьей модели диапазон ошибки составляет от -340 до 364

Самый минимальный диапазон также получился у третьей модели, что говорит нам об ее возможном успехе

### 5.4 Прогноз удоя коров
"""

cow_buy.head()

"""Добавляем недостающие признаки ЭКЕ (Энергетическая кормовая единица), Сырой протеин, г и СПО (Сахаро-протеиновое соотношение). И сравниваем готовые ДФ между собой по значениям столбцов."""

cow_buy['эке^2'] = ferma_main['эке^2'].mean() * 1.05
cow_buy['сырой протеин, г'] = ferma_main['сырой протеин, г'].mean() * 1.05
cow_buy['новое спо'] = ferma_main['новое спо']
cow_buy['эке (энергетическая кормовая единица)'] = ferma['эке (энергетическая кормовая единица)'].mean()*1.05
cow_buy['спо (сахаро-протеиновое соотношение)'] = ferma['спо (сахаро-протеиновое соотношение)'].mean()*1.05
cow_buy = cow_buy.rename(columns={'имя_папы': 'имя папы'})

cow_buy

X_test_ohe = ohe.transform(cow_buy[category])
X_test_scaled = scaler.transform(cow_buy[numeric])

columns_ohe = ohe.get_feature_names_out(category)
X_test_prepared = pd.DataFrame(
    np.hstack([X_test_ohe, X_test_scaled]),
    columns = list(columns_ohe) + numeric,
    index = cow_buy.index
)

cow_buy['прогноз удоя'] = model_three.predict(X_test_prepared.to_numpy())

cow_buy

"""### 5.5 Вывод

Протестировали три модели линейного машинного обучения. По метрикам выяснили, что третья допукает меньше всего ошибок. Пропустили данные ДФ cow_buy через модель и получили данные по прогнозу удоя коров, которых хочет приобрести фермер.

По таблице видно, что не все коровы дают больше 6 тысяч кг молока, но мы можем допустить также, что не все коровы идеально прогнозированы и следует присмотреться к доверительному интервалу от +365 до -337.

## 6 шаг. Обучение модели логистической регрессии

### 6.1 Модель логистической регрессии

Используем в качестве целевого признака Вкус молока, отделяем категориальные и количсевтенные признаки.
"""

ferma.head()

cols = ['сырой протеин, г', 'порода', 'тип пастбища', 'порода папы_быка', 'жирность,%',
        'белок,%', 'возраст', 'новое спо', 'эке^2', 'эке (энергетическая кормовая единица)',
        'спо (сахаро-протеиновое соотношение)', 'имя папы'
       ]

X = ferma[cols]
y = ferma['вкус молока']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    random_state=RANDOM_STATE
)

ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
scaler = StandardScaler()

category = ['порода', 'тип пастбища', 'порода папы_быка', 'возраст', 'новое спо', 'имя папы']
numeric = ['сырой протеин, г', 'жирность,%', 'белок,%', 'эке^2',
           'эке (энергетическая кормовая единица)', 'спо (сахаро-протеиновое соотношение)'
          ]

ohe = ohe.fit(X_train[category])
scaler = scaler.fit(X_train[numeric])

X_train_ohe = ohe.transform(X_train[category])
X_test_ohe = ohe.transform(X_test[category])

X_train_scaled = scaler.transform(X_train[numeric])
X_test_scaled = scaler.transform(X_test[numeric])

X_train_processed = np.hstack([X_train_ohe, X_train_scaled])
X_test_processed = np.hstack([X_test_ohe, X_test_scaled])

clf = LogisticRegression()
clf = clf.fit(X_train_processed, y_train)

y_pred = clf.predict(X_test_processed)

y_pred

y_test.value_counts()

X_test_processed.shape

len(y_test)

X_test_processed[:5]

y_test[:5]

y_proba = clf.predict_proba(X_test_processed)[:,1]
y_proba

"""### 6.2 Оценка качества модели на тестовой выборке: метрики accuracy, recall, precision."""

accuracy_score(y_test, y_pred)

recall_score(y_test, y_pred, pos_label='не вкусно')

precision_score(y_test, y_pred, pos_label='не вкусно')

y_proba = clf.predict_proba(X_test_processed)[:,1]

"""### 6.3 Матрица ошибок"""

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues_r')
plt.ylabel("True")
plt.xlabel("Predicted")
plt.title("Матрица ошибок вкуса молока")
plt.show()

"""1 - не вкусно

0 - вкусно

Логистическая регрессия предсказывает не сильно лучше линейной в нашем случае:

Модель правильно идентифицирует 85% положительных случаев

Только 60% предсказанных положительных случаев действительно верны

Общая точность тоже невысока

### 6.4 Сведение критичной ошибки к нулю
"""

threshold = 0.87
y_pred_custom = np.where(y_proba > threshold, 'вкусно', 'не вкусно')

y_pred_custom

cm = confusion_matrix(y_test, y_pred_custom)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues_r')
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Матрица ошибок вкуса молока")
plt.show()

recall_score(y_test, y_pred_custom, pos_label='не вкусно')

precision_score(y_test, y_pred_custom, pos_label='не вкусно')

thresholds = np.arange(0.5, 1, 0.01)
precisions = []
label_map = {'вкусно': 0, 'не вкусно': 1}
y_test_num = np.array([label_map[label] for label in y_test])

for t in thresholds:
    y_pred = (y_proba > t).astype(int)
    precision = precision_score(y_pred, y_test_num, pos_label=0, zero_division=0)
    precisions.append(precision)

plt.figure()
plt.plot(thresholds, precisions, marker='o')
plt.title('График точности')
plt.xlabel('Threshold')
plt.ylabel('Precision')
plt.grid(True)
plt.show()

precision_score(y_test, y_pred_custom, pos_label='вкусно')

"""**Выводы:** Ошибка первого рода критичнее, так как фермеру надо не купить коров, дающих невкусное молоко.

Чтобы получить такой результат потребовалось сменить границу на 0.16, но при этом сильно просели остальные ошибки и общая точность теста снизилась до 56%, не сильно, но у нас почти половина данных уже может быть неверно спрогнозирована, то есть деньги будут потрачены и не на всех коров с вкусным молоком, мы их упустим, что скажется в будущем на прибыли.

### 6.5 Прогноз вкуса молока
"""

cow_buy = cow_buy.rename(columns={
    'текущая_жирность,%': 'жирность,%',
    'текущий_уровень_белок,%': 'белок,%'
})

X_test_ohe = ohe.transform(cow_buy[category])
X_test_scaled = scaler.transform(cow_buy[numeric])

columns_ohe = ohe.get_feature_names_out(category)
X_test_prepared = pd.DataFrame(
    np.hstack([X_test_ohe, X_test_scaled]),
    columns = list(columns_ohe) + numeric,
    index = cow_buy.index
)

proba = clf.predict_proba(X_test_prepared.to_numpy())[:, 1]

cow_buy['прогноз вкуса'] = (proba >= 0.68).astype(int)

cow_buy

"""### 6.6 Выводы:

Коровка под индеком 12 принесет вкусное молока.

Логистическая модель показала себя хуже линейной на целевом признаке Вкус молока.

9 из 19 коров из желаемых скорее всего подойдут для удоя, но необходимо сверить удой и вкус.

## 7 Шаг. Итоговые выводы

### 7.1 Прогнозы вкуса молока и удоя коров «ЭкоФермы»
"""

filtered_cows = cow_buy[(cow_buy['прогноз удоя'] > 6000) & (cow_buy['прогноз вкуса'] == 1)]

filtered_cows

"""### 7.2 Выводы

На протяжении выполнения проекта мы:

- изучили данные, нашли дубликаты, работали с пропусками, преобразовали типы данных

- построили графики для категориальных и количественных признаков

- сделали расчет коэфициенты корреляции между всеми принаками и диаграммы рассеяния для всех количественных признаков

- разработали две модели машинного обучения для помощи фермеру в отборе коров, удовлетворяющих строгим критериям:

- спрогнозировали модель, которая предсказывает годовой надой (≥ 6000 кг).

- оценка вкуса молока, создали модель, которая определяет вероятность, что молоко будет соответствовать вкусовым стандартам.

Линейная регрессия больше подойдет для расчета прогноза удоя молока, логистическая же регрессия подойдет для определения, будет ли молоко "вкусным".

С минимальным риском для себя фермер может купить 1 корову, отсеянные по двум признакам в  ДФ filtered_cows.

Рекомендация фермеру - работать на гарантийных условиях, чтобы минимизировать риски, найти еще информацию по коровам, чтобы сделать модель максимально точной.

Обе модели подходят для анализа, но их можно улучшить добавив новые признаки, улучшив старые(привести в необходимый вид), работа с выбросами, кодирование категориальных признаков, масштабирование количественных и подбор порога.

Наши модели можно улучшить добавлением новых признаков, например, можно задуматься о здоровье коровы, условиях ее содержания, массе тела и тд.

Метрики, которые мы использовали:

- Precision: % коров, которые дейтельно дадут >6000 кг.

- Recall: % коров, которые не были пропущены.
"""